github: Prajwal-Koirala
patreon:
open_collective:
ko_fi: prajwalkoirala23
tidelift:
community_bridge:
liberapay: prajwalkoirala23
issuehunt: prajwal-koirala
otechie:
custom: paypal.me/prajwalkoirala23
BCH: qzq9ae4jlewtz7v7mn4tv7kav3dc9rvjwsg5f36099
BTC: 3QgnfTBaW4gn4y8QPEdXNJY6Y74nBwRXfR
DAI: 0x8DAd9f838d5F2Ab6B14795d47dD1Fa4ED7D1AcaB
ETC: 0xd42D20D7E1fC0adb98B67d36691754E3F944478A
ETH: 0xe000C5094398dd83A3ef8228613CF4aD134eB0EA
LTC: MVwkmnnaLDq7UccDeudcpQYwFnnDwDxxmq
XRP: rw2ciyaNshpHe7bCHo4bRWq6pqqynnWKQg (1790476900)
